spring:
  application:
    name: question5

  datasource:
    url: jdbc:postgresql://localhost:5432/quiz5
    username: postgres
    password: sifre123
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true